services:
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tetra
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  pg-data:
    driver: local
  redis-data:
    driver: local
